#include <cassert>
#include <cmath>

#include "color.hpp"

using Vector::vec;

namespace Color {

// Wyman, Sloane, Shirley, JCGT 2013
static double wss(double w, double c1, double c2) {
  double v = w * (w < 0 ? c1 : c2);
  return exp(-0.5 * v * v);
}

vec toXYZ(double wl) {
  return {
    0.362  * wss(wl - 442.0, 0.0624, 0.0374) +
    1.056  * wss(wl - 599.8, 0.0264, 0.0323) +
    -0.065 * wss(wl - 501.1, 0.0490, 0.0382),
    0.821  * wss(wl - 568.8, 0.0213, 0.0247) +
    0.286  * wss(wl - 530.9, 0.0613, 0.0322),
    1.217  * wss(wl - 437.0, 0.0845, 0.0278) +
    0.681  * wss(wl - 459.0, 0.0385, 0.0725)
  };
}

double const sumY = 106.946;

double toY(double wl) {
  double v =
    0.821  * wss(wl - 568.8, 0.0213, 0.0247) +
    0.286  * wss(wl - 530.9, 0.0613, 0.0322);
  return v / sumY;
}

Matrix::mat RGBtoXYZ = {
  0.49000, 0.31000, 0.20000,
  0.17697, 0.81240, 0.01063,
  0.00000, 0.01000, 0.99000
};

vec RGBtoY = { 0.17697, 0.81240, 0.01063 };

Matrix::mat XYZtoRGB = {
  2.36461385,  -0.89654057, -0.46807328,
  -0.51516621, 1.4264081,   0.0887581,
  0.0052037,   -0.01440816, 1.00920446
};

}

namespace Spectrum {

full_spectrum::full_spectrum() {
  fill(0.);
}

void add(full_spectrum &fs, sampled_wl const &wl, sampled_spectrum const &s) {
  for (int i = 0; i < nb_s; ++i) {
    int l = (wl.lambda[i] - min_wl) / (max_wl - min_wl) * nb_wl;
    assert(0 <= l && l < nb_wl);
    fs[l] += s[i] / wl.pdf[i];
  }
}

vec toXYZ(full_spectrum const &s) {
  vec c { 0., 0., 0. };
  for (int i = 0; i < nb_wl; ++i) {
    double t = (double)i / nb_wl;
    c += s[i] * Color::toXYZ((1 - t) * min_wl + t * max_wl);
  }
  return (1 / Color::sumY) * c;
}

blackbody::blackbody(double f, int t): temp(t) {
  int ml = 2.8977721e6 / temp;
  if (ml > max_wl) ml = max_wl;
  strength = f / aux(ml);
}

double blackbody::aux(double wl) const {
  double c = 299792458.;
  double h = 6.62606957e-34;
  double kb = 1.3806488e-23;
  double l = wl * 1e-9;
  double l2 = l * l, l5 = l2 * l2 * l;
  return 2 * h * c * c / (l5 * (exp((h * c) / (l * kb * temp)) - 1));
}

sampled_spectrum blackbody::sample(point2 const &, sampled_wl const &l) const {
  sampled_spectrum s;
  for (int i = 0; i < nb_s; ++i) {
    s[i] = aux(l.lambda[i]) * strength;
  }
  return s;
}

sampled::sampled(samples_t const &s): samples(s) {
  assert(s.size() != 0);
}

sampled_spectrum sampled::sample(point2 const &, sampled_wl const &wl) const {
  sampled_spectrum sp;
  for (int i = 0; i < nb_s; ++i) {
    double l = wl.lambda[i];
    int sb = 0, se = samples.size(), ss = se;
    while (se > sb + 1) {
      int sm = (sb + se) / 2;
      if (samples[sm].first <= l) sb = sm;
      else se = sm;
    }
    if (se == 0) sp[i] = samples[0].second;
    else if (se == ss) sp[i] = samples[se - 1].second;
    else {
      double l1 = samples[sb].first, l2 = samples[se].first;
      double f = (l - l1) / (l2 - l1);
      sp[i] = (1 - f) * samples[sb].second + f * samples[se].second;
    }
  }
  return sp;
}

sampled_spectrum from_wl::sample(point2 const &, sampled_wl const &wl) const {
  sampled_spectrum s;
  double w = max_wl - min_wl;
  for (int i = 0; i < nb_s; ++i) {
    double l = wl.lambda[i];
    if (l - lambda > 0.5 * w) { l -= w; }
    else if (lambda - l > 0.5 * w) { l += w; }
    double f = (l - lambda) / width;
    s[i] = fact * exp(-0.5 * f * f);
  }
  return s;
}

struct palette {
  static int const channels = 15;
  static int const scale = 20;
  static int const compact_sp[scale][scale];
  static double factors[scale][scale];
  palette();
  static sampled_spectrum geti(int x, int y, sampled_wl const &wl);
  static sampled_spectrum get(double x, double y, sampled_wl const &wl);
};

// 15*2-bit palette generated by the palette.cpp helper.
int const palette::compact_sp[scale][scale] = {
  { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, },
  { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, },
  { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, },
  { 0, 0, 0, 0x3c003003, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, },
  { 0, 0, 0, 0x3b003403, 0x3a403003, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, },
  { 0, 0, 0x3c003c07, 0x3f00340f, 0x3f00740b, 0x3f407007, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, },
  { 0, 0, 0x3d002c0f, 0x3f403c0e, 0x3f807c0b, 0x3ec0fc07, 0x3e41f407, 0x3e00c003, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, },
  { 0, 0, 0x3d00180f, 0x3e007d07, 0x3f40bd07, 0x3d01fd07, 0x3f51bc0f, 0x3ed1f40f, 0x3e11d001, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, },
  { 0, 0x3d000c07, 0x3e002d03, 0x3d803d0f, 0x3e40fe0f, 0x3f90bd0f, 0x3fd1fd0f, 0x3f93f907, 0x3fd7f80f, 0x3f4be003, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, },
  { 0, 0, 0x3c003e0b, 0x3f402c1f, 0x3f40fe1f, 0x3f81fd4f, 0x3fa1fd1f, 0x3f97fd1f, 0x3fdffd0f, 0x3fffbc0f, 0x3ff7d005, 0, 0, 0, 0, 0, 0, 0, 0, 0, },
  { 0, 0x3000040b, 0x3d002e0f, 0x39007d2f, 0x3f80bd57, 0x3f42fe5f, 0x3fd5fd5f, 0x3fe7fd5f, 0x3ffffe1f, 0x3fffe517, 0x3fef580f, 0x3ffdc007, 0, 0, 0, 0, 0, 0, 0, 0, },
  { 0, 0, 0x3d002f0b, 0x3d407f4b, 0x3f80fe6f, 0x3e94ff5f, 0x3f97ff6f, 0x3fdffe9f, 0x3fffb96f, 0x3fffd52f, 0x3ffe541f, 0x3fbd140f, 0x3f7d4007, 0, 0, 0, 0, 0, 0, 0, },
  { 0, 0, 0x3f001f03, 0x3f803e5f, 0x3d50ffaf, 0x3f55ffdb, 0x3fdbffef, 0x3ffffbbf, 0x3fff9d7f, 0x3fff555f, 0x3ffe451f, 0x3ffd101f, 0x3fac040b, 0x3ffd0001, 0, 0, 0, 0, 0, 0, },
  { 0, 0, 0x3d001f13, 0x3f007faf, 0x3f50ffff, 0x3fd5bfff, 0x3fedbfff, 0x3fffdbff, 0x3fff55bb, 0x3ffd455f, 0x3ffe045f, 0x3fec041f, 0x3ffc0103, 0x3fe4000f, 0x3f500001, 0, 0, 0, 0, 0, },
  { 0, 0, 0x3e000e17, 0x3f007fff, 0x3f607fff, 0x3fd56fff, 0x3ff65fff, 0x3ffe57ff, 0x3ffd467f, 0x3ffe019f, 0x3ff9005f, 0x3ffc002f, 0x37400004, 0x3090000a, 0, 0, 0, 0, 0, 0, },
  { 0, 0, 0x3d000f4b, 0x3f802fef, 0x3fd05fff, 0x3fd51fff, 0x3fe91bff, 0x3fbe07ff, 0x3ffd037f, 0x3ffc016f, 0x3fb4002f, 0x3df0001f, 0, 0, 0, 0, 0, 0, 0, 0, },
  { 0, 0, 0, 0x3f801fff, 0x3f601bff, 0x3fa417ff, 0x3ef507ff, 0x3ffc03ef, 0x3ff800bf, 0x3fe00027, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, },
  { 0, 0, 0, 0x3f400bbf, 0x3f4407ff, 0x3df007ff, 0x3fe401ff, 0x3b70007b, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, },
  { 0, 0, 0, 0x390005ff, 0x3f5002ff, 0x399000bb, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, },
  { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, },
};

double palette::factors[scale][scale];

palette::palette() {
  std::array<double, channels> r;
  r.fill(0.);
  for (int w = min_wl; w < max_wl; ++w) {
    int l = channels * (w - min_wl) / (max_wl - min_wl);
    r[l] += Color::toY(w);
  }
  for (int y = 0; y < scale; ++y) {
    for (int x = 0; x < scale; ++x) {
      int val = compact_sp[y][x];
      double f = 0;
      for (int l = 0; l < channels; ++l) {
        f += (3 & (val >> (2 * l))) * r[l];
      }
      factors[y][x] = f ? 1. / f : 1.;
    }
  }
}

sampled_spectrum palette::geti(int x, int y, sampled_wl const &wl) {
  sampled_spectrum s;
  assert(0 <= x && x < scale && 0 <= y && y < scale);
  int csp = compact_sp[y][x];
  double invc = (double)channels / (max_wl - min_wl);
  for (int i = 0; i < nb_s; ++i) {
    int l = invc * (wl.lambda[i] - min_wl);
    s[i] = 3 & (csp >> (2 * l));
  }
  s *= factors[y][x];
  return s;
}

sampled_spectrum palette::get(double x, double y, sampled_wl const &wl) {
  x = x * scale;
  y = (1. - y) * scale;
  int xi = x, yi = y, xj = xi + 1, yj = yi + 1;
  double xf = x - xi, yf = y - yi;
  sampled_spectrum sp[4] = {
    geti(xi, yi, wl), geti(xj, yi, wl),
    geti(xi, yj, wl), geti(xj, yj, wl)
  };
  sampled_spectrum pi = (1. - xf) * sp[0] + xf * sp[1];
  sampled_spectrum pj = (1. - xf) * sp[2] + xf * sp[3];
  sampled_spectrum s = (1. - yf) * pi + yf * pj;
  for (int i = 0; i < nb_s; ++i) {
    if (s[i] > 1.) s[i] = 1.;
  }
  return s;
}

palette palette;

sampled_spectrum xyY::sample(point2 const &, sampled_wl const &wl) const {
  return strength * palette::get(x, y, wl);
}

sampled_spectrum fromXYZ(vec const &c, sampled_wl const &wl) {
  double t = c[0] + c[1] + c[2];
  if (t == 0.) return sampled_spectrum(0.);
  return c[1] * palette::get(c[0] / t, c[1] / t, wl);
}

sampled_spectrum from_texture::sample(point2 const &uv, sampled_wl const &wl) const {
  int x = std::min<int>(uv[0] * img->width, img->width - 1);
  int y = std::min<int>((1 - uv[1]) * img->height, img->height - 1);
  vec c = img->read(x, y);
  return fromXYZ(Color::RGBtoXYZ * c, wl);
}

}
